name: Release

on:
  push:
    branches: ['master']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Actual Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.CR_PAT_BUILT_WITH_TAILWIND_CSS }}
          automatic_release_tag: 2.0.0
          draft: false
          prerelease: false
          files: built-with-tailwind-css.zip
          title: ${{ steps.package-version.outputs.current-version}}
