name: Release

on:
  push:
    branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn run build
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/build
        
  release:
    name: Release
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Actual Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with: 
           repo_token: ${{ secrets.CR_PAT_BUILT_WITH_TAILWIND_CSS }}
           automatic_release_tag: 1.0.0
           draft: false
           prerelease: false
           title: ${{ steps.package-version.outputs.current-version}}