name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          mkdir -p build
          (cd src && zip -r ../build/built-with-tailwind-css.zip .)

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release v${{ github.ref_name }}
          artifacts: "build/built-with-tailwind-css.zip"
          replacesArtifacts: true
          draft: false
          prerelease: false
          allowUpdates: true
          body: |
            **New Release v${{ github.ref_name }} - Built with Tailwind CSS**
            - Detects Tailwind CSS use in a web page.
            - Includes the latest updates to the Built with Tailwind CSS extension.
