name: Release

on:
  push:
    branches: ['master']

jobs:
  release:
    name: Push Docker image to DockerHub and GitHub Container Registry. Deploy image to Caprover.
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with: 
           repo_token: ${{ secrets.CR_PAT_BUILT_WITH_TAILWIND_CSS }}
           automatic_release_tag: latest
           draft: false
           prerelease: false
           title: ${{ steps.package-version.outputs.current-version}}