name: Zip Files

on:
  release:
    types: [published]

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - run: rm -r ./build && cp -R ./src ./build/
        
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: src
          dest: result.zip