name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: build/ manifest.json
          dest: result.zip
      - uses: actions/upload-artifact@v1
        with:
          name: zip
          path: ${{ github.workspace }}